import { db } from '@/db';
import { dropdownMasterNew } from '@/db/schema';

async function main() {
    const sampleData = [
        // Lead Source (7 records)
        {
            category: 'lead_source',
            value: 'website',
            label: 'Website',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_source',
            value: 'referral',
            label: 'Referral',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_source',
            value: 'social_media',
            label: 'Social Media',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_source',
            value: 'advertisement',
            label: 'Advertisement',
            displayOrder: 4,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_source',
            value: 'direct',
            label: 'Direct',
            displayOrder: 5,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_source',
            value: 'walk_in',
            label: 'Walk In',
            displayOrder: 6,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_source',
            value: 'other',
            label: 'Other',
            displayOrder: 7,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        // Lead Stage (8 records)
        {
            category: 'lead_stage',
            value: 'new',
            label: 'New',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_stage',
            value: 'contacted',
            label: 'Contacted',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_stage',
            value: 'qualified',
            label: 'Qualified',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_stage',
            value: 'demo_scheduled',
            label: 'Demo Scheduled',
            displayOrder: 4,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_stage',
            value: 'proposal_sent',
            label: 'Proposal Sent',
            displayOrder: 5,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_stage',
            value: 'negotiation',
            label: 'Negotiation',
            displayOrder: 6,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_stage',
            value: 'converted',
            label: 'Converted',
            displayOrder: 7,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_stage',
            value: 'lost',
            label: 'Lost',
            displayOrder: 8,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        // Lead Status (3 records)
        {
            category: 'lead_status',
            value: 'active',
            label: 'Active',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_status',
            value: 'inactive',
            label: 'Inactive',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'lead_status',
            value: 'junk',
            label: 'Junk',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        // Education Level (6 records)
        {
            category: 'education_level',
            value: 'high_school',
            label: 'High School',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'education_level',
            value: 'diploma',
            label: 'Diploma',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'education_level',
            value: 'bachelors',
            label: "Bachelor's Degree",
            displayOrder: 3,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'education_level',
            value: 'masters',
            label: "Master's Degree",
            displayOrder: 4,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'education_level',
            value: 'phd',
            label: 'PhD',
            displayOrder: 5,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'education_level',
            value: 'other',
            label: 'Other',
            displayOrder: 6,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        // Call Outcome (7 records)
        {
            category: 'call_outcome',
            value: 'answered',
            label: 'Answered',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'call_outcome',
            value: 'no_answer',
            label: 'No Answer',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'call_outcome',
            value: 'busy',
            label: 'Busy',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'call_outcome',
            value: 'callback_requested',
            label: 'Callback Requested',
            displayOrder: 4,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'call_outcome',
            value: 'not_interested',
            label: 'Not Interested',
            displayOrder: 5,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'call_outcome',
            value: 'interested',
            label: 'Interested',
            displayOrder: 6,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            category: 'call_outcome',
            value: 'converted',
            label: 'Converted',
            displayOrder: 7,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(dropdownMasterNew).values(sampleData);
    
    console.log('✅ Dropdown master seeder completed successfully - 35 records inserted');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});