import { db } from '@/db';
import { leadsNew } from '@/db/schema';

async function main() {
    const now = new Date();
    const sixtyDaysAgo = new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000);

    // Helper function to generate random date within last 60 days
    const getRandomDate = (start: Date, end: Date) => {
        return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime())).toISOString();
    };

    // Helper function to get updated date (same or after created date)
    const getUpdatedDate = (createdDate: string) => {
        const created = new Date(createdDate);
        const updated = new Date(created.getTime() + Math.random() * 30 * 24 * 60 * 60 * 1000);
        return updated > now ? now.toISOString() : updated.toISOString();
    };

    const sampleLeads = [
        // New leads (10 leads - 20%)
        {
            name: 'Rahul Sharma',
            email: 'rahul.sharma@gmail.com',
            phone: '+919876543210',
            whatsappNumber: '+919876543210',
            leadSource: 'website',
            leadStage: 'new',
            leadStatus: 'active',
            courseInterestId: 1,
            assignedTelecallerId: 3,
            assignedCounselorId: null,
            city: 'Mumbai',
            state: 'Maharashtra',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: null,
            notes: 'Interested in full-stack development course',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Priya Patel',
            email: null,
            phone: '+919123456789',
            whatsappNumber: null,
            leadSource: 'referral',
            leadStage: 'new',
            leadStatus: 'active',
            courseInterestId: 3,
            assignedTelecallerId: 4,
            assignedCounselorId: null,
            city: 'Ahmedabad',
            state: 'Gujarat',
            country: 'India',
            educationLevel: 'Undergraduate',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: null,
            notes: null,
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Amit Kumar',
            email: 'amit.kumar@yahoo.com',
            phone: '+919988776655',
            whatsappNumber: '+919988776655',
            leadSource: 'social_media',
            leadStage: 'new',
            leadStatus: 'active',
            courseInterestId: 2,
            assignedTelecallerId: 3,
            assignedCounselorId: null,
            city: 'Delhi',
            state: 'Delhi',
            country: 'India',
            educationLevel: 'Postgraduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Looking for weekend batches',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Sneha Reddy',
            email: 'sneha.reddy@outlook.com',
            phone: '+919445566778',
            whatsappNumber: '+919445566778',
            leadSource: 'website',
            leadStage: 'new',
            leadStatus: 'active',
            courseInterestId: 5,
            assignedTelecallerId: 4,
            assignedCounselorId: null,
            city: 'Hyderabad',
            state: 'Telangana',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: null,
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Vikram Singh',
            email: 'vikram.singh@gmail.com',
            phone: '+919112233445',
            whatsappNumber: null,
            leadSource: 'advertisement',
            leadStage: 'new',
            leadStatus: 'active',
            courseInterestId: null,
            assignedTelecallerId: null,
            assignedCounselorId: null,
            city: 'Jaipur',
            state: 'Rajasthan',
            country: 'India',
            educationLevel: 'High School',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: null,
            notes: 'Needs more information about course options',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Anjali Verma',
            email: 'anjali.verma@hotmail.com',
            phone: '+919876501234',
            whatsappNumber: '+919876501234',
            leadSource: 'website',
            leadStage: 'new',
            leadStatus: 'active',
            courseInterestId: 4,
            assignedTelecallerId: 3,
            assignedCounselorId: null,
            city: 'Pune',
            state: 'Maharashtra',
            country: 'India',
            educationLevel: 'Undergraduate',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: null,
            notes: 'Inquired about scholarship programs',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Deepak Gupta',
            email: null,
            phone: '+919334455667',
            whatsappNumber: '+919334455667',
            leadSource: 'referral',
            leadStage: 'new',
            leadStatus: 'active',
            courseInterestId: 7,
            assignedTelecallerId: 4,
            assignedCounselorId: null,
            city: 'Lucknow',
            state: 'Uttar Pradesh',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Unemployed',
            conversionDate: null,
            lostReason: null,
            notes: null,
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Kavita Nair',
            email: 'kavita.nair@gmail.com',
            phone: '+919223344556',
            whatsappNumber: null,
            leadSource: 'website',
            leadStage: 'new',
            leadStatus: 'active',
            courseInterestId: 6,
            assignedTelecallerId: 3,
            assignedCounselorId: null,
            city: 'Chennai',
            state: 'Tamil Nadu',
            country: 'India',
            educationLevel: 'Postgraduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Prefers online classes',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Arjun Mehta',
            email: 'arjun.mehta@yahoo.com',
            phone: '+919887766554',
            whatsappNumber: '+919887766554',
            leadSource: 'social_media',
            leadStage: 'new',
            leadStatus: 'inactive',
            courseInterestId: 8,
            assignedTelecallerId: null,
            assignedCounselorId: null,
            city: 'Bangalore',
            state: 'Karnataka',
            country: 'India',
            educationLevel: 'Undergraduate',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: null,
            notes: null,
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Neha Joshi',
            email: 'neha.joshi@outlook.com',
            phone: '+919665544332',
            whatsappNumber: '+919665544332',
            leadSource: 'website',
            leadStage: 'new',
            leadStatus: 'active',
            courseInterestId: 9,
            assignedTelecallerId: 4,
            assignedCounselorId: null,
            city: 'Kolkata',
            state: 'West Bengal',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Requested call back after 6 PM',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },

        // Contacted leads (12-13 leads - 25%)
        {
            name: 'Sanjay Kapoor',
            email: 'sanjay.kapoor@gmail.com',
            phone: '+919112244668',
            whatsappNumber: '+919112244668',
            leadSource: 'referral',
            leadStage: 'contacted',
            leadStatus: 'active',
            courseInterestId: 1,
            assignedTelecallerId: 3,
            assignedCounselorId: null,
            city: 'Mumbai',
            state: 'Maharashtra',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Had initial conversation, showing interest in data science',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Pooja Agarwal',
            email: 'pooja.agarwal@hotmail.com',
            phone: '+919334455889',
            whatsappNumber: null,
            leadSource: 'website',
            leadStage: 'contacted',
            leadStatus: 'active',
            courseInterestId: 2,
            assignedTelecallerId: 4,
            assignedCounselorId: null,
            city: 'Delhi',
            state: 'Delhi',
            country: 'India',
            educationLevel: 'Undergraduate',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: null,
            notes: 'First call completed, needs to discuss with parents',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Manoj Tiwari',
            email: null,
            phone: '+919776655443',
            whatsappNumber: '+919776655443',
            leadSource: 'social_media',
            leadStage: 'contacted',
            leadStatus: 'active',
            courseInterestId: 3,
            assignedTelecallerId: 3,
            assignedCounselorId: null,
            city: 'Lucknow',
            state: 'Uttar Pradesh',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Unemployed',
            conversionDate: null,
            lostReason: null,
            notes: 'Interested in job-oriented courses',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Ritu Singh',
            email: 'ritu.singh@gmail.com',
            phone: '+919556677889',
            whatsappNumber: '+919556677889',
            leadSource: 'advertisement',
            leadStage: 'contacted',
            leadStatus: 'active',
            courseInterestId: 5,
            assignedTelecallerId: 4,
            assignedCounselorId: null,
            city: 'Jaipur',
            state: 'Rajasthan',
            country: 'India',
            educationLevel: 'Postgraduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: null,
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Aditya Raj',
            email: 'aditya.raj@yahoo.com',
            phone: '+919445577889',
            whatsappNumber: null,
            leadSource: 'website',
            leadStage: 'contacted',
            leadStatus: 'active',
            courseInterestId: 4,
            assignedTelecallerId: 3,
            assignedCounselorId: null,
            city: 'Pune',
            state: 'Maharashtra',
            country: 'India',
            educationLevel: 'Undergraduate',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: null,
            notes: 'Reached out, waiting for response',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Divya Malhotra',
            email: 'divya.malhotra@outlook.com',
            phone: '+919223344778',
            whatsappNumber: '+919223344778',
            leadSource: 'referral',
            leadStage: 'contacted',
            leadStatus: 'active',
            courseInterestId: 6,
            assignedTelecallerId: 4,
            assignedCounselorId: null,
            city: 'Bangalore',
            state: 'Karnataka',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Contacted via WhatsApp, responded positively',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Karan Saxena',
            email: 'karan.saxena@gmail.com',
            phone: '+919887766990',
            whatsappNumber: '+919887766990',
            leadSource: 'website',
            leadStage: 'contacted',
            leadStatus: 'active',
            courseInterestId: 7,
            assignedTelecallerId: 3,
            assignedCounselorId: null,
            city: 'Hyderabad',
            state: 'Telangana',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Business Owner',
            conversionDate: null,
            lostReason: null,
            notes: 'Looking for corporate training options',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Swati Desai',
            email: null,
            phone: '+919665544221',
            whatsappNumber: null,
            leadSource: 'social_media',
            leadStage: 'contacted',
            leadStatus: 'active',
            courseInterestId: 8,
            assignedTelecallerId: 4,
            assignedCounselorId: null,
            city: 'Ahmedabad',
            state: 'Gujarat',
            country: 'India',
            educationLevel: 'Postgraduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: null,
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Rohit Pandey',
            email: 'rohit.pandey@hotmail.com',
            phone: '+919112233557',
            whatsappNumber: '+919112233557',
            leadSource: 'referral',
            leadStage: 'contacted',
            leadStatus: 'active',
            courseInterestId: 9,
            assignedTelecallerId: 3,
            assignedCounselorId: null,
            city: 'Chennai',
            state: 'Tamil Nadu',
            country: 'India',
            educationLevel: 'Undergraduate',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: null,
            notes: 'Initial conversation done, scheduling follow-up',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Meera Iyer',
            email: 'meera.iyer@yahoo.com',
            phone: '+919334455113',
            whatsappNumber: '+919334455113',
            leadSource: 'walk_in',
            leadStage: 'contacted',
            leadStatus: 'active',
            courseInterestId: 10,
            assignedTelecallerId: 4,
            assignedCounselorId: null,
            city: 'Kolkata',
            state: 'West Bengal',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Visited office, showed strong interest',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Varun Choudhary',
            email: 'varun.choudhary@gmail.com',
            phone: '+919776655221',
            whatsappNumber: null,
            leadSource: 'website',
            leadStage: 'contacted',
            leadStatus: 'inactive',
            courseInterestId: 1,
            assignedTelecallerId: 3,
            assignedCounselorId: null,
            city: 'Mumbai',
            state: 'Maharashtra',
            country: 'India',
            educationLevel: 'High School',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: null,
            notes: 'Not responding to follow-ups',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Priyanka Bhatt',
            email: 'priyanka.bhatt@outlook.com',
            phone: '+919445566332',
            whatsappNumber: '+919445566332',
            leadSource: 'advertisement',
            leadStage: 'contacted',
            leadStatus: 'active',
            courseInterestId: 2,
            assignedTelecallerId: 4,
            assignedCounselorId: null,
            city: 'Delhi',
            state: 'Delhi',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Unemployed',
            conversionDate: null,
            lostReason: null,
            notes: 'Contacted twice, seems interested',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },

        // Qualified leads (7-8 leads - 15%)
        {
            name: 'Rakesh Malhotra',
            email: 'rakesh.malhotra@gmail.com',
            phone: '+919112244335',
            whatsappNumber: '+919112244335',
            leadSource: 'referral',
            leadStage: 'qualified',
            leadStatus: 'active',
            courseInterestId: 1,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Mumbai',
            state: 'Maharashtra',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Qualified lead, budget confirmed, ready to proceed',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Anita Chopra',
            email: 'anita.chopra@hotmail.com',
            phone: '+919334455224',
            whatsappNumber: '+919334455224',
            leadSource: 'website',
            leadStage: 'qualified',
            leadStatus: 'active',
            courseInterestId: 3,
            assignedTelecallerId: 4,
            assignedCounselorId: 5,
            city: 'Delhi',
            state: 'Delhi',
            country: 'India',
            educationLevel: 'Postgraduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Verified background, meets all criteria',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Suresh Rao',
            email: 'suresh.rao@yahoo.com',
            phone: '+919776655889',
            whatsappNumber: null,
            leadSource: 'social_media',
            leadStage: 'qualified',
            leadStatus: 'active',
            courseInterestId: 2,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Bangalore',
            state: 'Karnataka',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Qualified for advanced course, financial capability confirmed',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Kritika Bose',
            email: null,
            phone: '+919556677442',
            whatsappNumber: '+919556677442',
            leadSource: 'referral',
            leadStage: 'qualified',
            leadStatus: 'active',
            courseInterestId: 5,
            assignedTelecallerId: 4,
            assignedCounselorId: null,
            city: 'Kolkata',
            state: 'West Bengal',
            country: 'India',
            educationLevel: 'Undergraduate',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: null,
            notes: 'Pre-qualified, waiting for counselor assignment',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Ajay Sinha',
            email: 'ajay.sinha@gmail.com',
            phone: '+919223344556',
            whatsappNumber: '+919223344556',
            leadSource: 'advertisement',
            leadStage: 'qualified',
            leadStatus: 'active',
            courseInterestId: 4,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Pune',
            state: 'Maharashtra',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Business Owner',
            conversionDate: null,
            lostReason: null,
            notes: 'Corporate training qualified lead',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Nisha Pillai',
            email: 'nisha.pillai@outlook.com',
            phone: '+919887766443',
            whatsappNumber: '+919887766443',
            leadSource: 'website',
            leadStage: 'qualified',
            leadStatus: 'active',
            courseInterestId: 6,
            assignedTelecallerId: 4,
            assignedCounselorId: 5,
            city: 'Chennai',
            state: 'Tamil Nadu',
            country: 'India',
            educationLevel: 'Postgraduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'All documentation verified, ready for demo',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Vishal Dubey',
            email: 'vishal.dubey@hotmail.com',
            phone: '+919665544998',
            whatsappNumber: null,
            leadSource: 'referral',
            leadStage: 'qualified',
            leadStatus: 'active',
            courseInterestId: 7,
            assignedTelecallerId: 3,
            assignedCounselorId: null,
            city: 'Lucknow',
            state: 'Uttar Pradesh',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Unemployed',
            conversionDate: null,
            lostReason: null,
            notes: 'Qualified based on aptitude test',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },

        // Demo scheduled (5 leads - 10%)
        {
            name: 'Harish Menon',
            email: 'harish.menon@gmail.com',
            phone: '+919112233889',
            whatsappNumber: '+919112233889',
            leadSource: 'website',
            leadStage: 'demo_scheduled',
            leadStatus: 'active',
            courseInterestId: 1,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Bangalore',
            state: 'Karnataka',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Demo scheduled for next week, highly interested',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Seema Khanna',
            email: 'seema.khanna@yahoo.com',
            phone: '+919334455667',
            whatsappNumber: '+919334455667',
            leadSource: 'referral',
            leadStage: 'demo_scheduled',
            leadStatus: 'active',
            courseInterestId: 3,
            assignedTelecallerId: 4,
            assignedCounselorId: 5,
            city: 'Delhi',
            state: 'Delhi',
            country: 'India',
            educationLevel: 'Postgraduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Demo class booked for data analytics course',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Gaurav Mishra',
            email: null,
            phone: '+919776655224',
            whatsappNumber: '+919776655224',
            leadSource: 'social_media',
            leadStage: 'demo_scheduled',
            leadStatus: 'active',
            courseInterestId: 2,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Hyderabad',
            state: 'Telangana',
            country: 'India',
            educationLevel: 'Undergraduate',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: null,
            notes: 'Virtual demo arranged, reminder sent',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Archana Kulkarni',
            email: 'archana.kulkarni@outlook.com',
            phone: '+919556677331',
            whatsappNumber: null,
            leadSource: 'advertisement',
            leadStage: 'demo_scheduled',
            leadStatus: 'active',
            courseInterestId: 5,
            assignedTelecallerId: 4,
            assignedCounselorId: 5,
            city: 'Pune',
            state: 'Maharashtra',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Demo confirmed for weekend batch',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Abhishek Jain',
            email: 'abhishek.jain@gmail.com',
            phone: '+919223344772',
            whatsappNumber: '+919223344772',
            leadSource: 'website',
            leadStage: 'demo_scheduled',
            leadStatus: 'active',
            courseInterestId: 4,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Ahmedabad',
            state: 'Gujarat',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Business Owner',
            conversionDate: null,
            lostReason: null,
            notes: 'Corporate demo scheduled with team',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },

        // Proposal sent (4 leads - 8%)
        {
            name: 'Nitin Agarwal',
            email: 'nitin.agarwal@hotmail.com',
            phone: '+919887766552',
            whatsappNumber: '+919887766552',
            leadSource: 'referral',
            leadStage: 'proposal_sent',
            leadStatus: 'active',
            courseInterestId: 1,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Mumbai',
            state: 'Maharashtra',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Proposal sent via email, waiting for approval',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Pallavi Shah',
            email: 'pallavi.shah@gmail.com',
            phone: '+919665544773',
            whatsappNumber: '+919665544773',
            leadSource: 'website',
            leadStage: 'proposal_sent',
            leadStatus: 'active',
            courseInterestId: 3,
            assignedTelecallerId: 4,
            assignedCounselorId: 5,
            city: 'Bangalore',
            state: 'Karnataka',
            country: 'India',
            educationLevel: 'Postgraduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Custom proposal sent, follow-up scheduled',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Manish Kaul',
            email: null,
            phone: '+919112233448',
            whatsappNumber: null,
            leadSource: 'social_media',
            leadStage: 'proposal_sent',
            leadStatus: 'active',
            courseInterestId: 2,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Delhi',
            state: 'Delhi',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Detailed proposal with payment plans shared',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Reena Saxena',
            email: 'reena.saxena@yahoo.com',
            phone: '+919334455889',
            whatsappNumber: '+919334455889',
            leadSource: 'advertisement',
            leadStage: 'proposal_sent',
            leadStatus: 'active',
            courseInterestId: 5,
            assignedTelecallerId: 4,
            assignedCounselorId: 5,
            city: 'Jaipur',
            state: 'Rajasthan',
            country: 'India',
            educationLevel: 'Undergraduate',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: null,
            notes: 'Proposal reviewed, negotiating terms',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },

        // Negotiation (3-4 leads - 7%)
        {
            name: 'Siddharth Kapoor',
            email: 'siddharth.kapoor@outlook.com',
            phone: '+919776655443',
            whatsappNumber: '+919776655443',
            leadSource: 'referral',
            leadStage: 'negotiation',
            leadStatus: 'active',
            courseInterestId: 1,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Mumbai',
            state: 'Maharashtra',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Negotiating payment terms and start date',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Tanvi Reddy',
            email: 'tanvi.reddy@gmail.com',
            phone: '+919556677224',
            whatsappNumber: null,
            leadSource: 'website',
            leadStage: 'negotiation',
            leadStatus: 'active',
            courseInterestId: 3,
            assignedTelecallerId: 4,
            assignedCounselorId: 5,
            city: 'Hyderabad',
            state: 'Telangana',
            country: 'India',
            educationLevel: 'Postgraduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Discussing EMI options and course customization',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },
        {
            name: 'Akhil Verma',
            email: 'akhil.verma@hotmail.com',
            phone: '+919223344885',
            whatsappNumber: '+919223344885',
            leadSource: 'social_media',
            leadStage: 'negotiation',
            leadStatus: 'active',
            courseInterestId: 2,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Pune',
            state: 'Maharashtra',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: null,
            notes: 'Price negotiation in progress, very close to closing',
            createdAt: getRandomDate(sixtyDaysAgo, now),
            updatedAt: getRandomDate(sixtyDaysAgo, now),
        },

        // Converted (5 leads - 10%)
        {
            name: 'Rajiv Thakur',
            email: 'rajiv.thakur@gmail.com',
            phone: '+919887766221',
            whatsappNumber: '+919887766221',
            leadSource: 'referral',
            leadStage: 'converted',
            leadStatus: 'active',
            courseInterestId: 1,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Mumbai',
            state: 'Maharashtra',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: new Date('2024-02-15').toISOString(),
            lostReason: null,
            notes: 'Successfully enrolled in Full Stack Development course',
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Ishita Banerjee',
            email: 'ishita.banerjee@yahoo.com',
            phone: '+919665544112',
            whatsappNumber: '+919665544112',
            leadSource: 'website',
            leadStage: 'converted',
            leadStatus: 'active',
            courseInterestId: 3,
            assignedTelecallerId: 4,
            assignedCounselorId: 5,
            city: 'Kolkata',
            state: 'West Bengal',
            country: 'India',
            educationLevel: 'Postgraduate',
            currentOccupation: 'Working Professional',
            conversionDate: new Date('2024-02-20').toISOString(),
            lostReason: null,
            notes: 'Enrolled in Data Science program, payment completed',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            name: 'Ashwin Nair',
            email: 'ashwin.nair@outlook.com',
            phone: '+919112233996',
            whatsappNumber: null,
            leadSource: 'social_media',
            leadStage: 'converted',
            leadStatus: 'active',
            courseInterestId: 2,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Chennai',
            state: 'Tamil Nadu',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: new Date('2024-02-25').toISOString(),
            lostReason: null,
            notes: 'Converted to Digital Marketing course, very satisfied',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            name: 'Shruti Mehta',
            email: 'shruti.mehta@hotmail.com',
            phone: '+919334455997',
            whatsappNumber: '+919334455997',
            leadSource: 'referral',
            leadStage: 'converted',
            leadStatus: 'active',
            courseInterestId: 4,
            assignedTelecallerId: 4,
            assignedCounselorId: 5,
            city: 'Bangalore',
            state: 'Karnataka',
            country: 'India',
            educationLevel: 'Undergraduate',
            currentOccupation: 'Student',
            conversionDate: new Date('2024-03-01').toISOString(),
            lostReason: null,
            notes: 'Enrolled in UI/UX Design course with scholarship',
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            name: 'Karthik Ramesh',
            email: 'karthik.ramesh@gmail.com',
            phone: '+919776655339',
            whatsappNumber: '+919776655339',
            leadSource: 'advertisement',
            leadStage: 'converted',
            leadStatus: 'active',
            courseInterestId: 5,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Hyderabad',
            state: 'Telangana',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: new Date('2024-03-05').toISOString(),
            lostReason: null,
            notes: 'Successfully joined AI & Machine Learning course',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },

        // Lost (2-3 leads - 5%)
        {
            name: 'Preeti Sinha',
            email: 'preeti.sinha@yahoo.com',
            phone: '+919556677885',
            whatsappNumber: null,
            leadSource: 'website',
            leadStage: 'lost',
            leadStatus: 'inactive',
            courseInterestId: 1,
            assignedTelecallerId: 3,
            assignedCounselorId: 5,
            city: 'Delhi',
            state: 'Delhi',
            country: 'India',
            educationLevel: 'Graduate',
            currentOccupation: 'Working Professional',
            conversionDate: null,
            lostReason: 'Budget constraints - found course too expensive',
            notes: 'Could not proceed due to financial reasons',
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Mohit Yadav',
            email: null,
            phone: '+919223344669',
            whatsappNumber: '+919223344669',
            leadSource: 'referral',
            leadStage: 'lost',
            leadStatus: 'junk',
            courseInterestId: null,
            assignedTelecallerId: 4,
            assignedCounselorId: null,
            city: 'Lucknow',
            state: 'Uttar Pradesh',
            country: 'India',
            educationLevel: 'High School',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: 'No response - multiple follow-up attempts failed',
            notes: 'Marked as junk after no response for 30 days',
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Lalita Gupta',
            email: 'lalita.gupta@outlook.com',
            phone: '+919887766774',
            whatsappNumber: '+919887766774',
            leadSource: 'social_media',
            leadStage: 'lost',
            leadStatus: 'inactive',
            courseInterestId: 3,
            assignedTelecallerId: 3,
            assignedCounselorId: null,
            city: 'Jaipur',
            state: 'Rajasthan',
            country: 'India',
            educationLevel: 'Undergraduate',
            currentOccupation: 'Student',
            conversionDate: null,
            lostReason: 'Joined competitor - opted for different institution',
            notes: 'Lost to competitor offering lower fees',
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
    ];

    await db.insert(leadsNew).values(sampleLeads);
    
    console.log('✅ Leads seeder completed successfully - 50 leads created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});